### ISSUE TITLE
Host command with `mv` might not work for Windows users?

### ISSUE THREAD

**Issue by mandrasch** [holas1337/ddev-sylius#1]
Hi, just saw this on twitter! Nice! 👏 

Just as quick feedback because I saw it while checking it out:  

Running this line as host command 

https://github.com/holas1337/ddev-sylius/blob/main/.ddev/commands/host/files-import#L14 

might not work for DDEV users on Windows (legacy) since `mv` is not available (if I'm not mistaken)?

Don't know about Windows WSL2, should work there.  

In case of legacy windows detecting the operating system is maybe needed, see .eg.  https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/launch#L84

But I guess it would be just easier to run these things in the web container via web/container commands + also easier to maintain. https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#container-commands

Just wanted to let you know, feel free to close.

Much success with this, Cheers!

**Comment by holas1337** [comment]
Hi @mandrasch 
Sorry for my late response but I don't have much free time ;) 
From what I know using WSL2 should work and as for the bare Windows I don't have this system so I will not be able to check it or support it.

I will check when I will have some time if this can be run from the web container instead of from the host.

Thanks for checking and feedback.

**Comment by rfay** [comment]
What some other add-ons do for tools that may be missing in certain environments (like `jq` ) or for tools that behave differently in different environments (like base64) is to do the action with [ddev-utilities](https://hub.docker.com/r/ddev/ddev-utilities), which would work here as well. 

Examples: 
* Use of [grep and awk](https://github.com/ddev/ddev/blob/17abdad60b13f2ccd04505c70af30726e0c49709/pkg/ddevapp/global_dotddev_assets/commands/host/launch#L63)
* Use of [sed in ddev-redis-7](https://github.com/ddev/ddev-redis-7/blob/f3be6ad1ed4bab1ee7eedc92884f4933c3b161d2/install.yaml#L20)

**Comment by mandrasch** [comment]
Interesting 💡

@holas1337 you're welcome. I'll close this issue since it seems to be an rare edge case for the add-on👍Cool that WSL handles it.
